# Generated by Django 5.0.2 on 2024-03-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0002_job_text_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
    ]
