# Generated by Django 5.0.2 on 2024-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0003_rename_description_job_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='text_notification',
        ),
    ]
