# Generated by Django 5.0.2 on 2024-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0004_remove_job_text_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_notification', models.CharField(max_length=100)),
            ],
        ),
    ]
