# Generated by Django 5.0.2 on 2024-03-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0006_savejob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='savejob',
        ),
    ]
